// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TEMPERATURE MessageType = 0
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEMPERATURE",
	}
	MessageType_value = map[string]int32{
		"TEMPERATURE": 0,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

type TemperatureMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MType         MessageType            `protobuf:"varint,1,opt,name=m_type,json=mType,proto3,enum=messages.MessageType" json:"m_type,omitempty"`
	MTemperature  float32                `protobuf:"fixed32,2,opt,name=m_temperature,json=mTemperature,proto3" json:"m_temperature,omitempty"`
	MTimeStamp    int64                  `protobuf:"varint,3,opt,name=m_timeStamp,json=mTimeStamp,proto3" json:"m_timeStamp,omitempty"`
	MDeviceId     uint64                 `protobuf:"varint,4,opt,name=m_deviceId,json=mDeviceId,proto3" json:"m_deviceId,omitempty"`
	MSensorId     uint64                 `protobuf:"varint,5,opt,name=m_sensorId,json=mSensorId,proto3" json:"m_sensorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureMessage) Reset() {
	*x = TemperatureMessage{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureMessage) ProtoMessage() {}

func (x *TemperatureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureMessage.ProtoReflect.Descriptor instead.
func (*TemperatureMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TemperatureMessage) GetMType() MessageType {
	if x != nil {
		return x.MType
	}
	return MessageType_TEMPERATURE
}

func (x *TemperatureMessage) GetMTemperature() float32 {
	if x != nil {
		return x.MTemperature
	}
	return 0
}

func (x *TemperatureMessage) GetMTimeStamp() int64 {
	if x != nil {
		return x.MTimeStamp
	}
	return 0
}

func (x *TemperatureMessage) GetMDeviceId() uint64 {
	if x != nil {
		return x.MDeviceId
	}
	return 0
}

func (x *TemperatureMessage) GetMSensorId() uint64 {
	if x != nil {
		return x.MSensorId
	}
	return 0
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\bmessages\"\xc6\x01\n" +
	"\x12TemperatureMessage\x12,\n" +
	"\x06m_type\x18\x01 \x01(\x0e2\x15.messages.MessageTypeR\x05mType\x12#\n" +
	"\rm_temperature\x18\x02 \x01(\x02R\fmTemperature\x12\x1f\n" +
	"\vm_timeStamp\x18\x03 \x01(\x03R\n" +
	"mTimeStamp\x12\x1d\n" +
	"\n" +
	"m_deviceId\x18\x04 \x01(\x04R\tmDeviceId\x12\x1d\n" +
	"\n" +
	"m_sensorId\x18\x05 \x01(\x04R\tmSensorId*\x1e\n" +
	"\vMessageType\x12\x0f\n" +
	"\vTEMPERATURE\x10\x00B,Z*github.com/ViktorVolga/SH-MQTTServer/protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_messages_proto_goTypes = []any{
	(MessageType)(0),           // 0: messages.MessageType
	(*TemperatureMessage)(nil), // 1: messages.TemperatureMessage
}
var file_proto_messages_proto_depIdxs = []int32{
	0, // 0: messages.TemperatureMessage.m_type:type_name -> messages.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
